pr: none
trigger: none

variables:
- group: devopsforai-aml-vg

stages:
- stage: 'Dev'
  displayName: 'Dev'
  jobs:
  - job: "Provision_Dev"
    displayName: "Provision Dev resources"
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 0
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'AzureResourceConnection'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(RESOURCE_GROUP)'
        location: $(LOCATION)
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/environment_setup/arm-templates/cloud-environment.json'
        overrideParameters: '-baseName $(BASE_NAME) -location $(LOCATION) -workspace $(WORKSPACE_NAME)'
        deploymentMode: 'Incremental'
      displayName: 'Deploy OH resources to Azure'
